### ISSUE TITLE
更新新版本后，在选择更新数据后程序崩溃

### ISSUE THREAD

**Issue by MirrorCubeSquare** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#53]
系统Win11，程序本体正常（而且更新数据的数据本身是更新成功了的，只是返回菜单的时候似乎是渲染失败？）
尝试过选项中的各种组合（包括将所有X去除后点更新）
以下是调试信息
Unhandled exception. System.InvalidOperationException: Encountered malformed markup tag at position 118.
   at Spectre.Console.MarkupTokenizer.MoveNext() in /_/src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 58
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 19
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117
   at Spectre.Console.AnsiConsole.MarkupLine(String value) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 81
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.DownloadAssets(ProgressContext ctx, String instruction, String path)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<>c__DisplayClass5_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Update(Boolean dataOnly)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.ShowMenu()
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.Main(String[] args)
   at UmamusumeResponseAnalyzer.UmamusumeResponseAnalyzer.<Main>(String[] args)

**Comment by EtherealAO** [comment]
频道应该要等到今晚零点自动扩容之后才能加
